# Generated by Django 3.0.5 on 2020-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=225, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('account_level', models.CharField(default='Not Available', max_length=20)),
                ('wallet_balance', models.CharField(default='0', max_length=50)),
                ('deposit_amount', models.CharField(default='0', max_length=50)),
                ('trade_profit', models.CharField(default='0', max_length=50)),
                ('total_balance', models.CharField(default='0', max_length=50)),
                ('trade_progress', models.IntegerField(default='0')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
