# Generated by Django 3.0.5 on 2020-08-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200806_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_not_verified',
            field=models.BooleanField(default=True),
        ),
    ]
