# Generated by Django 3.0.5 on 2020-08-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200806_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_otp',
            field=models.IntegerField(default='000000', max_length=8),
        ),
    ]
