# Generated by Django 3.0.5 on 2020-08-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_verify_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_otp',
            field=models.IntegerField(default='000000'),
        ),
    ]
