# Generated by Django 3.0.5 on 2020-08-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200806_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdraw_not_eligable',
            field=models.BooleanField(default=True),
        ),
    ]
