# Generated by Django 3.0.5 on 2020-08-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_withdraw_not_eligable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=300)),
                ('withdraw_amount', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
