# Generated by Django 3.0.5 on 2020-08-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userwithdrawrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerWalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_wallet_address', models.CharField(max_length=500)),
                ('eth_wallet_address', models.CharField(max_length=500)),
            ],
        ),
    ]
