# Generated by Django 3.0.5 on 2020-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_managerwalletaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithdrawrequest',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
