# Generated by Django 3.0.5 on 2020-08-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userwithdrawrequest_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepositRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('deposit_amount', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_payment_proof/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
