# Generated by Django 3.0.5 on 2020-08-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='plantinum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='silver',
            field=models.BooleanField(default=False),
        ),
    ]
