# Generated by Django 3.0.5 on 2020-08-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200810_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='plantinum',
            new_name='platinum',
        ),
    ]
