# Generated by Django 3.0.5 on 2020-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_managercontactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentPayouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=200)),
                ('amount_invested', models.CharField(max_length=50)),
                ('payout_amount', models.CharField(max_length=50)),
                ('payout_date', models.DateTimeField()),
                ('account_type', models.CharField(max_length=30)),
            ],
        ),
    ]
