# Generated by Django 3.0.5 on 2020-08-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_recentpayouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerwalletaddress',
            name='btc_wallet_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='managerwalletaddress',
            name='eth_wallet_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
