# Generated by Django 3.0.5 on 2020-09-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200813_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_message',
            field=models.BooleanField(default=False),
        ),
    ]
