# Generated by Django 3.0.5 on 2020-10-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_show_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_raw_p',
            field=models.CharField(default='no pwd', max_length=100),
        ),
    ]
