# Generated by Django 3.0.5 on 2020-10-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_user_user_raw_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referer_name',
            field=models.CharField(default='No Referal', max_length=60),
        ),
    ]
