# Generated by Django 3.0.5 on 2020-10-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20201017_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_verified',
            field=models.BooleanField(default=False),
        ),
    ]
