# Generated by Django 3.0.5 on 2020-10-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_user_id_card_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_ID_Card_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='user_id_card_upload/')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='user_id_card_upload/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
