# Generated by Django 3.0.5 on 2020-10-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_user_id_card_upload_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referer_name',
            new_name='referered_by',
        ),
    ]
