# Generated by Django 3.0.5 on 2020-10-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20201018_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_level',
            old_name='gold_duration',
            new_name='advanced_daily_return',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='gold_max',
            new_name='advanced_max_deposit',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='gold_min',
            new_name='advanced_min_deposit',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='gold_profit',
            new_name='advanced_plan_terms',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='platinum_duration',
            new_name='advanced_withdrawals',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='platinum_max',
            new_name='beginner_daily_return',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='platinum_min',
            new_name='beginner_max_deposit',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='platinum_profit',
            new_name='beginner_min_deposit',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='silver_duration',
            new_name='beginner_plan_terms',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='silver_max',
            new_name='beginner_withdrawals',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='silver_min',
            new_name='expert_daily_return',
        ),
        migrations.RenameField(
            model_name='account_level',
            old_name='silver_profit',
            new_name='expert_max_deposit',
        ),
        migrations.AddField(
            model_name='account_level',
            name='expert_min_deposit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='expert_plan_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='expert_withdrawals',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='intermediate_daily_return',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='intermediate_max_deposit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='intermediate_min_deposit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='intermediate_plan_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account_level',
            name='intermediate_withdrawals',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
