# Generated by Django 3.0.5 on 2021-03-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20210312_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='advanced',
            new_name='bronze',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='beginner',
            new_name='gold',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='expert',
            new_name='platinum',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='intermediate',
            new_name='silver',
        ),
    ]
