# Generated by Django 3.0.5 on 2021-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20210313_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_level',
            field=models.CharField(default='No Active Plan', max_length=20),
        ),
    ]
