# Generated by Django 3.0.5 on 2021-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20210313_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_level',
            field=models.CharField(default='Not Active', max_length=20),
        ),
    ]
