# Generated by Django 3.0.5 on 2021-03-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20210314_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWithdrawRequestOtherMethod',
        ),
    ]
