# Generated by Django 3.0.5 on 2021-03-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20210324_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='contact_request',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
