# Generated by Django 3.0.5 on 2021-05-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_auto_20210324_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_verified',
            field=models.BooleanField(default=True),
        ),
    ]
